server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # Petite config cache (pour production)
  location ~* \.(css|js|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public";
  }
}

